# Generated by Django 6.0.1 on 2026-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ID_kart',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='tugulgan_kun',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
